### ISSUE TITLE
[FEATURE] API & Events

### ISSUE THREAD

**Issue by JaxkDev** [jackthehack21/JukeBox-pmmp#9]
## Brief description:
Mostly aimed at adding new events useful for other plugins to be able to cancel and add even more custom configurations.

## Proposed Methods (Events):
BaseEvent():
 - RecordPlayingEvent(Item $record, Block $jukebox, Player $player = null)
 - RecordStopEvent(Block $jukebox, Player $player = null)
 - JukeboxPlacedEvent(Block $jukebox, Player $player = null)
 - JukeboxDestroyEvent(Block $jukebox, Player $player = null)

## Todo List:
- [x] Add new base event extended by all other internal plugin events.
- [x] Add base events (See above methods for list)
- [x] Call events and use data from events (possibly changed data from plugins)
- [x] Test all events using a external plugin.

**Comment by JaxkDev** [comment]
Added, And tested using 3rd party plugin.
